version: '3.8'

services:

  shop-item-microservice:
    image: 'shop-item-microservice:latest'
    build:
      context: ./
    container_name: shop-item-microservice
    ports:
      - '8080:8080'

